name: model-training
on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: iterative/setup-cml@v1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Train model and post CML report
        env:
          REPO_TOKEN: ${{ secrets.GITSHUB_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}  # This makes the root folder importable as a module
        run: |
          mkdir -p logs
          python breast_cancer_classification/modeling/train.py

          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
